Update master.yml

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -79,7 +79,7 @@ jobs:
 
 
   buildForLinux:
-    needs: test
+   # needs: test
     if: contains(github.ref, 'master') || contains(github.ref, 'Skins-and-buildings')
     name: Build for ${{ matrix.targetPlatform }}
     runs-on: ubuntu-latest
@@ -97,21 +97,25 @@ jobs:
           path: Library
           key: Library-${{ matrix.targetPlatform }}
       - name: Install Blender
-        run: 
-              sudo apt-get update;
-              sudo apt-get install -y wget xz-utils;
-              sudo wget https://download.blender.org/release/Blender3.6/blender-3.6.0-linux-x64.tar.xz;
-              sudo tar -xvf blender-3.6.0-linux-x64.tar.xz;
-              sudo mv blender-3.6.0-linux-x64 /opt/blender;
-              sudo ln -s /opt/blender/blender /usr/bin/blender;
-              sudo rm -rf blender-3.6.0-linux-x64.tar.xz
-              blender --version;
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y wget xz-utils
+          wget https://download.blender.org/release/Blender3.6/blender-3.6.0-linux-x64.tar.xz
+          tar -xvf blender-3.6.0-linux-x64.tar.xz
+          sudo mv blender-3.6.0-linux-x64 /opt/blender
+          sudo ln -s /opt/blender/blender /usr/bin/blender
+          blender --version
 
-      - name: Clean up Blender tar file
-        run: rm blender-3.6.0-linux-x64.tar.xz
+      - name: Verify Blender Installation
+        run: |
+          if ! command -v blender &> /dev/null; then
+            echo "Blender could not be found"
+            exit 1
+          else
+            echo "Blender is installed and available"
+            blender --version
+          fi
 
-      - name: Reset Git changes (if needed)
-        run: git reset --hard
       - uses: game-ci/unity-builder@v4.2.3
         env:
           UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
